<?php

namespace AppBundle\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM AppBundle:Agent a
                WHERE a.status = :status'
            )
            ->setParameter('status', 'Active')
            ->getResult();
    }

    public function findInactive()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM AppBundle:Agent a
                WHERE a.status = :status'
            )
            ->setParameter('status', 'Inactive')
            ->getResult();
    }
}
