<?php

namespace AppBundle\Repository;

/**
 * InstallationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHotInstallations()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i
                FROM AppBundle:Installation i
                WHERE i.hotStatus = :status'
            )
            ->setParameter('status', 'Yes')
            ->getResult();
    }

    public function getMissingConfirmation()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i
                FROM AppBundle:Installation i
                WHERE i.orderConfirmation is Null'
            )
            ->getResult();
    }


}
