<?php

namespace AppBundle\Repository;

/**
 * ModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModificationsByInstallationId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m
                FROM AppBundle:Modification m
                WHERE m.installationId = :installationId'
            )
            ->setParameter('installationId', $id)
            ->getResult();
    }
}
